operacoes_latex = {
    "E": "$\\mathrm{E}$",
    "C3": "$\\mathrm{C}_{3}$",
    "C3²": "$\\mathrm{C}_{3}^{2}$",
    "C2": "$\\mathrm{C}_{2}$",
    "C2_1": "$\\mathrm{C}_{2}^{(a)}$",
    "C2_1": "$\\mathrm{C}_{2}^{(b)}$",
    "C2_1": "$\\mathrm{C}_{2}^{(c)}$",
    "C2′_1": "$\\mathrm{C}_{2}^{\\prime(a)}$",
    "C2′_2": "$\\mathrm{C}_{2}^{\\prime(b)}$",
    "C2′_3": "$\\mathrm{C}_{2}^{\\prime(c)}$",
    "σv": "$\\sigma_{v}$",
    "σv_2": "$\\sigma_{v2}$",
    "σv_3": "$\\sigma_{v3}$",
    "σh": "$\\sigma_{h}$",
    "σd": "$\\sigma_{d}$",
    "σd_2": "$\\sigma_{d2}$",
    "i": "$\\mathrm{i}$",
    "S3": "$\\mathrm{S}_{3}$",
    "S3²": "$\\mathrm{S}_{3}^{2}$",
    "S3⁵": "$\\mathrm{S}_{3}^{5}$",
    "S6": "$\\mathrm{S}_{6}$",
    "S6⁵": "$\\mathrm{S}_{6}^{5}$",
    "C4": "$\\mathrm{C}_{4}$",
    "C4⁻¹": "$\\mathrm{C}_{4}^{-1}$",
    "C6": "$\\mathrm{C}_{6}$",
    "C6⁵": "$\\mathrm{C}_{6}^{5}$"
}